services:
    caniplanner_php:
        container_name: caniplanner_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./symfony:/www/symfony
        depends_on:
            -   caniplanner_pg
        networks:
            - caniplanner
        expose:
            - 9000
        environment:
            DATABASE_URL: "postgresql://melany:test123@caniplanner_pg:5432/caninpg_bd"
            KERNEL_CLASS: 'App\Kernel'
            APP_ENV: test
            APP_SECRET: "$$ecretf0rt3st"
            SYMFONY_DEPRECATIONS_HELPER: 999999
            JWT_PASSPHRASE: 'caniplanner123'
            JWT_SECRET_KEY: '%kernel.project_dir%/config/jwt/private.pem'
            JWT_PUBLIC_KEY: '%kernel.project_dir%/config/jwt/public.pem'

    caniplanner_server:
        container_name: caniplanner_server
        image: nginx:1.25-alpine3.18
        restart: unless-stopped
        working_dir: /www
        volumes:
            - ./symfony:/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   caniplanner_php
        networks:
            - caniplanner
        ports:
            - '80:8080'
        expose:
            - 8080

    caniplanner_pg:
        container_name: caniplanner_pg
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: melany
            POSTGRES_PASSWORD: test123
            POSTGRES_DB: caninpg_bd
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - caniplanner
        ports:
            - "5432:5432"
        expose:
            - 5432

networks:
    caniplanner:

volumes:
    pgdata:
