services:
    caniplanner_php:
        container_name: caniplanner_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile


        # user: "1000"
        volumes:
            - ./symfony:/www/symfony
            #environment:
            #  DATABASE_URL: ${DATABASE_URL}

    caniplanner_server:
        container_name: caniplanner_server
        image: nginx:1.25-alpine3.18
        restart: unless-stopped
        working_dir: /www
        volumes:
            - ./symfony:/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - '8080:80'

    caniplanner_pg:
        container_name: caniplanner_pg
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
