services:
    caniplanner_php:
        container_name: caniplanner_php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - ./symfony:/www/symfony
        depends_on:
            -   caniplanner_pg
        networks:
            - caniplanner
        expose:
            - 9000
        environment:
            JWT_PASSPHRASE: ${JWT_PASSPHRASE}

    caniplanner_server:
        container_name: caniplanner_server
        image: nginx:1.25-alpine3.18
        restart: unless-stopped
        working_dir: /www
        volumes:
            - ./symfony:/www/symfony
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            -   caniplanner_php
        networks:
            - caniplanner
        ports:
            - '8080:80'
        expose:
            - 8080

    caniplanner_pg:
        container_name: caniplanner_pg
        image: postgres:16-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        networks:
            - caniplanner
        ports:
            - "5432:5432"
        expose:
            - 5432

networks:
    caniplanner:

volumes:
    pgdata: