apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 3
    selector:
        matchLabels:
            app: mysql
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                -   name: mysql
                    image: mysql:8
                    env:
                        -   name: MYSQL_DATABASE
                            value: db_symfony
                        -   name: MYSQL_USER
                            value: m2i
                        -   name: MYSQL_PASSWORD
                            value: monsuperbecode
                        -   name: MYSQ_ROOT_PASSWORD
                            value: rootpass
                    resources:
                        limits:
                            memory: "512Mi"
                            cpu: "500m"
                        requests:
                            memory: "256Mi"
                            cpu: "250m"
                    ports:
                        -   containerPort: 3306
                    volumeMounts:
                        -   mountPath: /var/lib/mysql
                            name: mysql-storage
            volumes:
                -   name: mysql-storage
                    persistentVolumeClaim:
                      claimName: mysql-pvc