apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports: 
            - containerPort: 80
          volumeMounts: 
            - mountPath: /var/www/html/symfony
              name: symfony-volume
            - mountPath: /etc/nginx/conf.d
              name: conf-nginx
      volumes:  
        - name: symfony-volume
        - name: conf-nginx  
          configMap: 
            name: conf-nginx