security:
    # Définit le hachage des mots de passe pour l'entité User
    password_hashers:
        App\Entity\User:
            algorithm: auto

    # Déclare le provider qui va chercher les utilisateurs par email
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:

        # Pour le dev (profiler, assets), on désactive la sécurité
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        # Firewall pour toutes les routes API + authentification par JWT
        api:
            pattern: ^/api
            stateless: true
            jwt: ~

        # Firewall principal (utile pour login web, admin...)
        main:
            lazy: true
            provider: app_user_provider
            logout:
                path: app_logout

    #Règles d'accès globales
    access_control:
        - { path: ^/api/login, roles: PUBLIC_ACCESS }
        - { path: ^/api/register, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
