name: Symfony (Docker + SonarCloud)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  symfony-tests:
    runs-on: ubuntu-latest
    environment: app-dog-trainer

    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      SONAR_USER: ${{ secrets.SONAR_USER }}
      SONAR_PASSWORD: ${{ secrets.DOCKER_USER }}
      SONAR_DB: ${{ secrets.SONAR_DB }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      APP_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Copy .env.test.local
        run: cp symfony/.env.test symfony/.env.test.local

      - name: Build containers
        run: docker compose build

      - name: Start containers
        run: docker compose up -d

      - name: Run PHPUnit with coverage
        run: docker compose exec -T caniplanner_php sh -c "XDEBUG_MODE=coverage APP_ENV=test ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml"

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v5
        with:
          projectBaseDir: symfony
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
